### ISSUE TITLE
Update "wait" utility functions for tests with Selenium Wait API

### ISSUE THREAD

**Issue by valentijnnieman** [plotly/dash-renderer#103]
There are a couple of functions we're using in our tests, for example the `wait_for` style functions in the `utils.py` file, that we could update to use https://selenium-python.readthedocs.io/waits.html instead of our own functions.

**Comment by alexcjohnson** [comment]
@byronz I'm going to close this one, I think you have a good handle on `wait_for` and have already made some changes along the lines suggested here.
