### ISSUE TITLE
Make lint fail build when there are linting errors

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-renderer#106]
The current ```npm lint``` command has the ```--quiet```, which means that when running this command in CI and will not fail the build.

Suggest splitting this in two commands
- ```lint``` checks and fails on linting errors
- ```lint.fix``` checks and fixes linting errors if it can (retaining the current dev-side work case)

**Comment by alexcjohnson** [comment]
@valentijnnieman fixed this in #75
