### ISSUE TITLE
Fallback for CDN libs

### ISSUE THREAD

**Issue by jimr** [plotly/dash-renderer#11]
$ curl -I https://unpkg.com/react@15.4.2/dist/react.min.js
    HTTP/1.1 404 Not Found
    Date: Wed, 16 Aug 2017 08:53:46 GMT

The versions hosted on CDNJS seem fine: 

    $ curl -I https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.min.js
    HTTP/1.1 200 OK
    Date: Wed, 16 Aug 2017 08:55:22 GMT

Maybe it's a good idea to do a HEAD request on the CDN libs at app initialization & fall back to an alternate CDN or local versions of the files if they're not found?

**Comment by MartinKolarik** [comment]
Lots of people have been complaining about random 404 and 503 unpkg responses recently. You can always use jsDelivr instead, which works in a similar way but is more reliable: https://cdn.jsdelivr.net/npm/react@15.4.2/dist/react.min.js

**Comment by radumas** [comment]
Solution from :point_up: works on heroku as well:
```python
app.css.config.serve_locally = True
app.scripts.config.serve_locally = True
```

**Comment by chriddyp** [comment]
Yeah, a fallback seems like a good idea.

**Comment by chriddyp** [comment]
Some users reporting another issue with `unpkg` this morning. This is the 3rd time that we've had issues with the CDN since July.
Other CDN options:
- cdnjs
- cdn.jsdelivr
- Roll our own CDN with fastly and S3 (that's what we do for plotly.js https://github.com/plotly/plotly.js/)
- Any others out there?

**Comment by MartinKolarik** [comment]
@chriddyp switching to jsDelivr is definitely a good idea, we built it specifically for production usage with multiple failover levels (unpkg wasn't built to be used in production although some people started using it as such).

I'd also advise against rolling your own solution with S3 - it most likely wouldn't be more reliable than unpkg.

**Comment by jtpio** [comment]
> However, the issues have not lasted for a long time, so perhaps just a simple fallback to local would suffice for now

We experienced the issue for more than 12 hours before rolling out a fix as mentioned in the forum:
https://community.plot.ly/t/dash-renderer-0-11-1-dash-renderer-bundle-js/7179/16

If unpkg was never meant to be used in production, I would also go for a different default CDN like cdnjs or cdn.jsdelivr.

**Comment by alexcjohnson** [comment]
Closing as we merge this repo with the main dash repo. Anyway in dash 1.0 the default will change to `serve_locally=True` https://github.com/plotly/dash/pull/722

I have no strong feelings about any of the CDNs mentioned here vs unpkg, but if anyone would like to make a clear case for a different one - and accompany it with a PR to the main repo after the dash+renderer merge - we'd be be more than happy to switch!
