### ISSUE TITLE
Remove redux-logger?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-renderer#117]
The redux logger causes a ton of output in the console, especially with hot loading.

Also, sometimes it catches component error messages and rethrows them, making the tracebacks & "launch debugger on uncaught exceptions" tools hard to use.

I'm in favor of removing redux-logger. If anyone benefits from this while developing `dash-renderer`, they can add it back while they are in development (but not commit it).

Here's an associated community report that is having trouble filtering out the logs: https://community.plot.ly/t/dash-renderer-dev-js-logs-messes-my-browser-console/19120

**Comment by T4rk1n** [comment]
Agreed, also I added redux dev tools, it can be used to see the store update instead. https://github.com/plotly/dash-renderer/pull/107
