### ISSUE TITLE
NotifyObservers propTypes not correct

### ISSUE THREAD

**Issue by valentijnnieman** [plotly/dash-renderer#121]
I have noticed that the props in the `NotifyObservers` component don't have their propTypes set correctly = `path` is used in the code as `paths` and `dependencies`, `setProps` are missing. Small fix, just documenting it here.

**Comment by alexcjohnson** [comment]
We don't have a `NotifyObservers` component anymore, just a `notifyObservers` function. Pretty sure this issue is obsolete.
