### ISSUE TITLE
Breaking change between v. 0.19.0 and 0.20.0

### ISSUE THREAD

**Issue by simon-k** [plotly/dash-renderer#135]
Hi

I have a dash version. I'm using these components:

dash==0.28.2
dash-html-components==0.13.2
dash-core-components==0.30.2

Suddenly I experienced that my application wouldn't work anymore. It would just stick at the "Loading..." page. 

I investigated and found that dash-renderer was automatically updated to 0.20.0. That must be where there is a breaking change. Because if I revert to 0.19.0 the page is working. 

I know semver says that you can't rely on major version 0, but still. It would be nice if the changelog would mention that there was a breaking change.

**Comment by Marc-Andre-Rivet** [comment]
@simon-k Thanks for reporting this. There was no intended breaking change between dash-renderer 0.19.0 and 0.20.0.

dash and dash-renderer are intertwined and should be upgraded in tandem, this is reflected by the locked dependencies versioning starting with dash==0.37.0. It is quite possible that the new dash-renderer has unexpected behavior when combined with the relatively old dash==0.28.2 (October 2018).

Can you confirm if the problem still occurs if running the latest version of dash / components and if so could you provide a reproducible example?

**Comment by ned2** [comment]
I wonder if this might have been caused by the other Dash libraries being
pinned, while dash-renderer was not?

**Comment by simon-k** [comment]
I can confirm that my application is working after upgrading the dependencies to dash 0.39.0, so I'm pretty sure this is a case of the dash-renderer version not being pinned in the dash libraries like @ned2 suggests.

**Comment by simon-k** [comment]
A bot off topic:
The documentation https://dash.plot.ly/installation implies that you should install 

dash, dash-html-components, dash-core-components, dash-table==3.6.0 and ash-daq. But they all seem to be included in the dash library, so why not just state that as the required installation package?

**Comment by alexcjohnson** [comment]
> so why not just state that as the required installation package?

Yep, we're addressing that now 😅 https://github.com/plotly/dash-docs/pull/444

**Comment by alexcjohnson** [comment]
Closed - we're now fully version-locked based on your `dash` version.
