### ISSUE TITLE
More 'official' releases?

### ISSUE THREAD

**Issue by cpsievert** [plotly/dash-renderer#15]
It'd be great if this repo could use a release process similar to plotly.js (which makes it really for me to update dependencies in the R package), that is:

* Do a GitHub release for every version bump.
* For every release, include minified bundle(s) in a `dist/` folder.

**Comment by chriddyp** [comment]
@cpsievert  - can you use the bundles that are included on NPM? For example, https://unpkg.com/dash-renderer@0.7.4/dash_renderer/bundle.js

**Comment by cpsievert** [comment]
I can. And that's what I'm doing for now. 

It'd just be a bit easier for me to do upgrades down-the-road. Do you anticipate having to make a lot updates to the renderer? Or is it basically complete?

**Comment by chriddyp** [comment]
There will be a lot of updates to it. OK, I'll start making releases for all of these packages as well.

**Comment by cpsievert** [comment]
It'd also be helpful to have easy access to an official *non*-minified bundle (currently, `dash_renderer/bundle.js` is minified)
