### ISSUE TITLE
Provide metadata for react components

### ISSUE THREAD

**Issue by cpsievert** [plotly/dash-renderer#16]
As in https://github.com/plotly/dash-renderer/tree/master/src/components/core

Would allow me to use the same process I'm already using to curate components from:

https://github.com/plotly/dash-html-components/blob/master/lib/metadata.json
https://github.com/plotly/dash-core-components/blob/master/dash_core_components/metadata.json

**Comment by chriddyp** [comment]
@cpsievert - Those two links _are_ the metadata links for the react components. The components inside `dash-renderer` are not available to the end-user through the API, they are components that are used internally in dash-renderer to render the application.
