### ISSUE TITLE
Hot reloading only working once (reappearance?)

### ISSUE THREAD

**Issue by mmorin71828** [plotly/dash-renderer#178]
Hot reloading only working once. Appear to be the same issue as https://github.com/plotly/dash/issues/634, that was supposed to be fixed, but it appeared today.

Reinstalling anaconda and dash + rebooting didn't fix the issue.

**Comment by alexcjohnson** [comment]
@mmorin71828 this repo is obsolete, it has been merged into the main `dash` repo (for now anyway `dash-renderer` is still a separate Python package, but it no longer lives in its own repo)

Can you open an issue at https://github.com/plotly/dash/issues and give some more details? dash/python/os/browser versions, and the specific things you've tried that don't work. (changing python files? changing assets like css?)
