### ISSUE TITLE
Passing in nested arrays as children silently fails with `component.type` is undefined

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-renderer#23]

**Comment by rmarren1** [comment]
This is caught by https://github.com/plotly/dash/issues/340

**Comment by Buuntu** [comment]
I am getting a similar error, not sure what the cause is.  Was this fixed? All of my pages are displaying this error on the frontend.

**Comment by Buuntu** [comment]
I am getting weird callback issues (like not being called or not redisplaying the output when updated) and am wondering if this is the cause.

**Comment by alexcjohnson** [comment]
This should not be an issue any more with the recent dev tools improvements
