### ISSUE TITLE
Allow to set a custom Loading react component

### ISSUE THREAD

**Issue by Akronix** [plotly/dash-renderer#33]
In our organization, we want to use a custom Loading react component. [I've forked this repo and added our own component](https://github.com/Grasia/dash-renderer/tree/akronix), but I guess it would be better if anyone could have the option to import an external react component [here](https://github.com/plotly/dash-renderer/blob/04bd97a849cba04b70e69f4914004f511262181e/src/AppContainer.react.js), instead of maintaining a forked version.
This way we could even share different loading components accross all the Dash and React community.

**Comment by chriddyp** [comment]
>  I've forked this repo and added our own component

Note that it should be possible to use the main branch and add an external stylesheet that targets `_dash-loading-callback`, as in the discussion here: https://community.plot.ly/t/mega-dash-loading-states/5687

Of course, in that scenario you are limited in the complexity of the loading component (you would have to use content `:after` selector).

> it would be better if anyone could have the option to import an external react component here, instead of maintaining a forked version

Yeah! I would like to see a few things here:
1 - Ability to render a standard dash component (python components) 
2 - Ability to target loading states of individual components, e.g. show an overlay over _just_ the graphs or disable in the input components

**Comment by Akronix** [comment]
> Note that it should be possible to use the main branch and add an external stylesheet that targets _dash-loading-callback, as in the discussion here: https://community.plot.ly/t/mega-dash-loading-states/5687
> 
> Of course, in that scenario you are limited in the complexity of the loading component (you would have to use content :after selector).

That limitation is too much for our interests as we wanted to have our own HTML and JS behaviour for this.

**Comment by chriddyp** [comment]
There is a new master issue for this topic here: https://github.com/plotly/dash/issues/267
