### ISSUE TITLE
Inconsistent comment

### ISSUE THREAD

**Issue by akhmerov** [plotly/dash-renderer#34]
The comment [here](https://github.com/plotly/dash-renderer/blob/master/src/actions/index.js#L332) states that in case an event triggers a callback, the json will contain `event: {'id': 'graph', 'event': 'click'}`. Despite that, a [few lines below](https://github.com/plotly/dash-renderer/blob/master/src/actions/index.js#L341) we see `payload.event = event;`.

I am not sure which behavior is intended, however I would strongly prefer the one specified by the comment because I'd like to get the event emitter, and because the backend is free to disregard information it doesn't need.

**Comment by akhmerov** [comment]
NB: because the backend currently does not make use of the `event` entry in the request body, this change does not break compatibility with `dash`.

**Comment by alexcjohnson** [comment]
@akhmerov apologies that nobody ever addressed this issue. Events aren't even a thing anymore... closing.
