### ISSUE TITLE
Loading class that is the _parent_ of the app container

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-renderer#58]
Right now, the `._dash-loading-indicator` class is a cousin of the app container. If it was the parent, then you could customize UI in your `app.layout` that would only appear while a callback is being executed:

```
app.layout = html.Div(className='display-on-loading', children='Loading')
```

```
.display-on-loading {
    display: none;   
}
._dash-loading-indicator  .display-on-loading {
    display: block;
}
```

**Comment by alexcjohnson** [comment]
I'm assuming this is closed by the loading states API https://github.com/plotly/dash-renderer/pull/93 https://community.plot.ly/t/loading-states-and-loading-component/19650 - if there's anything still relevant here please reopen in the `dash` repo.
