### ISSUE TITLE
Why version.py file says that we are in version 0.13.1?

### ISSUE THREAD

**Issue by Akronix** [plotly/dash-renderer#74]
In current master branch, the [version.py file](https://github.com/plotly/dash-renderer/blob/master/dash_renderer/version.py) says that dash-renderer is in version 0.13.1, but according to the CHANGELOG.md the last version is 0.13.2 as is the [last version in pypi](https://pypi.org/project/dash_renderer/).

**Comment by rmarren1** [comment]
oops, we will just update that: https://github.com/plotly/dash-renderer/pull/78
