### ISSUE TITLE
missing a fetch polyfill?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-renderer#87]
I've tested this in IE11 myself, so I'm surprised by this bug report, but perhaps we're missing a fetch polyfill: https://community.plot.ly/t/on-ie11-getting-error-script5009-fetch-is-undefined/14445

**Comment by chriddyp** [comment]
@valentijnnieman - could you look into this one?

**Comment by valentijnnieman** [comment]
@chriddyp Can you invite me to Browserstack?

**Comment by T4rk1n** [comment]
I think we might have lost the `whatwg-fetch` polyfill with the webpack config changes, it needs to be added to the entry in `webpack.config.js`

**Comment by valentijnnieman** [comment]
I added it back in in #86

**Comment by chriddyp** [comment]
OK cool, let's get #86 merged and released ASAP then

**Comment by chriddyp** [comment]
Yikes, it looks like we're missing a few polyfills here. @valentijnnieman et al, we should just include the babel polyfill: https://babeljs.io/docs/en/babel-polyfill

**Comment by chriddyp** [comment]
I'll look into adding this now so that we can get out the fix asap

**Comment by chriddyp** [comment]
polyfill PR https://github.com/plotly/dash-renderer/pull/89

**Comment by chriddyp** [comment]
@mbkupfer - New release at `pip install dash-renderer==0.14.3`. Could you try it out?

**Comment by mbkupfer** [comment]
@chriddyp - Just tested it and everything looks great! Hooray for IE compatibility!!! :raised_hands:

**Comment by chriddyp** [comment]
🙌 🙌 🙌

**Comment by adamkgoldfarb** [comment]
+1 for "works for me"! IE is looking great. Thanks for the quick response!
