### ISSUE TITLE
dash dev tools UI

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-renderer#94]
Mocks here: https://www.figma.com/proto/icviajRVLhC69Ud0OW7dKe/dev-tools?node-id=162%3A2

This involves two things:
1. Providing a CSS file to re-skin the werkzeug debugger
2. Implementing the dash dev tools UI in the `dash-renderer` library.

@rmarren1 has written the skeleton UI for dash dev tools https://github.com/plotly/dash-renderer/pull/64. @valentijnnieman will work off that branch to implement the UI on top of it.

**Comment by chriddyp** [comment]
To start, we'll leave out the callback graph and the dev tools UI. We'll implement these in later PRs

**Comment by valentijnnieman** [comment]
> To start, we'll leave out the callback graph and the dev tools UI. We'll implement these in later PRs

So just style the werkzeug debugger first?

**Comment by chriddyp** [comment]
> and the dev tools UI

Sorry, I misspoke here. I meant the "Live Reload" UI and the "Callback Graph"
![image](https://user-images.githubusercontent.com/1280389/48960204-92293980-ef1f-11e8-9007-423de3e856ec.png)

**Comment by T4rk1n** [comment]
HotReload should be easy to disable/enable. Just need to stop the interval and restart it. Tell me if you need help.

**Comment by valentijnnieman** [comment]
I have a couple of questions about the design! I noticed the front end error cards say "clicking an alert takes the user to it's 'expanded view' in the alerts tray", but I don't see any designs for the expanded view, nor for the alerts tray. Am I missing something? I also cannot find designs for how the werkzeug debugger is supposed to be styled.

**Comment by chriddyp** [comment]
@valentijnnieman - The style for the werkzeug debugger are on pages 12-16:
![image](https://user-images.githubusercontent.com/1280389/49972672-5d961580-ff00-11e8-9e17-872235c40793.png)

**Comment by valentijnnieman** [comment]
@chriddyp  I just noticed there are multiple designs. I've been going off the "lo-fi" designs, which is what is linked in this issue, and as they were presented in presentation mode in Figma, I didn't think anything of it. The "hi-fi" designs indeed include the werkzeug debugger. I assume that the "hi-fi" designs are the ones I should've built. 

Spend a good bit of time building this: 
<img width="1097" alt="screen shot 2018-12-13 at 10 31 32 pm" src="https://user-images.githubusercontent.com/6509622/49981649-e162f880-ff26-11e8-8cf3-8da07cba9105.png">
 
Shouldn't be THAT much work to reskin them though.

**Comment by valentijnnieman** [comment]
@chriddyp Ugh, if I click on the link now, it does go to hi-fo mode. My bad. Not sure what happened.

**Comment by alexcjohnson** [comment]
Dev tools UI is a thing. Any remaining issues with it please open a new issue in `dash`
