### ISSUE TITLE
Set (or optionally set) `setProps` even if the component has no shared dependencies

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-renderer#98]
In dash-renderer 0.13.2 a component will have `setProps === undefined` if there is not dependency on its properties.

Complex components behavior can be severely impacted if they have no dependency (e.g. if no dash-table prop is used as a dependency, pagination_settings and filter expression are not updated, which prevents the UI from updating itself & shows incorrect information).

Complex components lend themselves well to this problem as there's a higher probability that they are at the top of the component "food-chain" (they depend on others but no one depends on them as they are the "final" view or result for a combination of settings)

*** Update: Do we need to do something similar for ```fireEvent``` ?

**Comment by alexcjohnson** [comment]
Resolved by #126 if I'm understanding the issue correctly. (and `fireEvent` is 🔪 )
