### ISSUE TITLE
rendering dynamic components with inputs that exist on the page

### ISSUE THREAD

**Issue by bakirillov** [plotly/dash-renderer#99]
Hello.

Doesn't work when is rendered in a tab. 
Example:
elif tab == "tab-2":
        return(
            html.Div([
             dash_table.DataTable(
              id='table',
              columns=[{"name": i, "id": i} for i in df.columns],
              data=df.to_dict("rows"),
              )
            ])
        )
df is empty DataFrame with 5 columns.
When "tab-2" is selected, the tab changes but the contents of previously selected tab remain. 
Could you please look into that?

**Comment by bakirillov** [comment]
That did not solve anything. The example still doesn't work.
And I don't understand why I can neither select nor filter the table despite it being selectable and filterable.

**Comment by bakirillov** [comment]
Selecting and filtering worked with dash-table-experiments (without tabs).

**Comment by chriddyp** [comment]
> That did not solve anything. 

Sorry, I wasn't clear enough. I know that it doesn't solve anything - this is a bug in `dash-renderer` that we need to fix in order for that example to work.

**Comment by bakirillov** [comment]
Ok, got it. Good luck!)

**Comment by alexcjohnson** [comment]
The example @chriddyp posted above had some errors, but those became obvious when I tried to run it just now, and after I fix them this all seems to work as you'd expect - so it looks to me as though this bug has been fixed accidentally sometime in the last 6 months? Here's the updated example, the table initially has data 1,2,3 but after clicking the update button in the other tab it has 5,6,7 when I switch back:

```py
import dash
import dash_table
import pandas as pd
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import json

external_stylesheets = ["https://codepen.io/chriddyp/pen/bWLwgP.css"]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.title = "Minimal tab error example"
app.layout = html.Div([
    dcc.Tabs(id="tabs", value="tab-1", children=[
        dcc.Tab(label="Some tab", value="tab-1"),
        dcc.Tab(label="Second tab", value="tab-2")
    ]),
    html.Div(id='table-store'),
    html.Div(id="tabs-content")
])
app.config['suppress_callback_exceptions'] = True

@app.callback(
    Output("tabs-content", "children"),
    [Input("tabs", "value")])
def render_content(tab):
    df = pd.DataFrame(
        {"A": [1, 2, 3], "B": [1, 2, 3]},
        columns=["A", "B"]
    )
    if tab == "tab-1":
        return(
            html.Div([
                "Dash version: "+dash.__version__, html.Br(),
                "Dash Table version: "+dash_table.__version__, html.Br(),
                "Dash Core Components version: "+dcc.__version__, html.Br(),
                "Dash HTML Components version: "+html.__version__,
                html.Button("Change the data in the table", id="gobutton")
            ])
        )
    elif tab == "tab-2":
        return(
            html.Div([
                dash_table.DataTable(
                    id='table',
                    columns=[{"name": i, "id": i} for i in df.columns],
                    data=df.to_dict("records"),
                    sorting=True,
                    row_selectable="single",
                    filtering=True
                )
            ])
        )

@app.callback(
    Output("table-store", "children"),
    [Input("gobutton", "n_clicks")]
)
def on_click(n_clicks):
    df = pd.DataFrame(
        {"A": [5, 6, 7], "B": [5, 6, 7]},
        columns=["A", "B"]
    )
    if n_clicks:
        return json.dumps(df.to_dict("records"))

@app.callback(
    Output("table", "data"),
    [Input("table-store", "children")]
)
def update_rows(rows):
    print(rows)
    if not rows:
        raise dash.exceptions.PreventUpdate
    return json.loads(rows)

if __name__ == '__main__':
    app.run_server(debug=True)
```

So I'm going to close this, but if you're still seeing this or a related problem please open a new issue in the main `dash` repo, as we're merging `dash-renderer` in there.
